# Generated by Django 3.2.8 on 2021-11-25 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(default='defaultroom', max_length=1000000),
        ),
    ]
